---
title: "Welcome to manfactuRail"
description: |
  Hi! I am a mechanical engineer with the Indian Railways. I've been with the organization for over 30 years now. My experience is in the areas of maintenance, repair and manufacture of rolling stock. I am passionate about manufacturing - in particular about applying scientific methods to analyze and improve manufacturing operations.
author:
  - name: K Raman
    url: https://raman-k.github.io/
    affiliation: Rail Wheel Factory Yelahanka
    affiliation_url: https://rwf.indianrailways.gov.in
date: 10-04-2022
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

Manufacturing, maintenance and repair of railway rolling stock require a strong technical foundation. In this blog, I will use the term manufacturing to cover manufacturing, maintenance and repair.

The institutional knowledge within the technical cadres of Indian Railways, is deep and strong. The cadres comprise of a diverse set of personnel starting from technicians to senior managers. Each sub-set of the cadre brings with it a set of competencies.

While the junior levels in the cadre are a repository of practical experience, they often lack the ability to articulate their thoughts in a manner that leads to better decision making. At the same time, in most cases, they are limited by the experience that they have gained in their careers.

The senior managers come with a strong theoretical background in engineering. At least in the initial part of their careers, they lack experience in the specialized areas of rolling stock manufacturing. Even with many years of experience, they do not have a thorough "hands-on" feel of what goes into the activities related to manufacturing of rolling stock. They however bring to the table the much needed breadth of perspective - such as strategic planning, selection of technology, identifying training needs etc.

Between these two levels is the sub-set of supervisors. Apart from functioning as field level managers in a 24x7x365 mode of operation, they serve as a bridge between the technicians and the senior managers. In many ways, they are the back bone of the technical cadre - as they ensure continuity of operational strategies that have been established over the years.

The entire cadre exists to carry out activities pertaining to manufacture of rolling stock - and to solve problems that are encountered in course of pursuing these activities.

There are two common approaches to solving these problems. The first is to identify the symptom and treat it and hope that the symptom is also the root cause. For example, if a bolt breaks, then it is replaced. The cause of the failure is attributed to the quality of the material. Usually, no further investigation is carried out to find out if there could be other reasons for the failure of the bolt.

The second approach is to go one step further and "modify" the system. Some of the common examples of this are one or more of the following:

-   Modify the system with additional factor of safety (e.g. replace M16 bolts with M20, or provide an additional bolt)

-   Add redundancy

-   Increase the frequency of maintenance attention

-   Provide a "by-passing" feature

### **Remember**

### Factor of safety $\large \propto$ Factor of ignorance

Often, these steps do not guarantee a permanent fix to the problem. Because, the system is not well understood, we introduce "rules" to control the problems. Some of these include launching a "drive" to weed out potential failures, increasing the frequency and level of "inspection", fixing responsibility on personnel etc.

In this blog I argue that there is a third alternative - adopting scientific methods to examine the problem. This approach is seldom pursued. We need to understand the system from the basics and approach the problem by asking "What is the cause?" rather than "who is responsible?".
